openapi: "3.1.0"
info:
  title: "backend API"
  description: "backend API"
  version: "1.0.0"
servers:
- url: "https://backend"
paths:
  /competitions/{id}:
    get:
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Competition"
  /competitions/ids:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  type: "integer"
                  format: "int32"
  /create-account:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUser"
        required: true
      responses:
        "200":
          description: ""
          content:
            '*/*':
              schema:
                type: "object"
  /games/{id}:
    get:
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Game"
  /games/{id}/action/{action}:
    post:
      description: ""
      parameters:
      - name: "action"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Player"
  /games/ids:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  type: "integer"
                  format: "int32"
  /competitions:
    post:
      description: ""
      responses:
        "200":
          description: ""
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    Competition:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        currentGameId:
          type: "integer"
          format: "int32"
        gameIds:
          type: "array"
          items:
            type: "integer"
            format: "int32"
      required:
      - "gameIds"
    CreateUser:
      type: "object"
      properties:
        name:
          type: "string"
        password:
          type: "string"
      required:
      - "name"
    Game:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        gridSize:
          type: "integer"
          format: "int32"
        pits:
          type: "integer"
          format: "int32"
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        password:
          type: "string"
        admin:
          type: "boolean"
        shirtColor:
          type: "string"
        trouserColor:
          type: "string"
        skinColor:
          type: "string"
      required:
      - "name"
      - "shirtColor"
      - "trouserColor"
      - "skinColor"
    Coordinate:
      type: "object"
      properties:
        x:
          type: "integer"
          format: "int32"
        "y":
          type: "integer"
          format: "int32"
    Player:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        user:
          $ref: "#/components/schemas/User"
        gameId:
          type: "integer"
          format: "int32"
        direction:
          type: "string"
          enum:
          - "NORTH"
          - "EAST"
          - "SOUTH"
          - "WEST"
        perceptions:
          type: "array"
          items:
            type: "string"
            enum:
            - "STENCH"
            - "BREEZE"
            - "GLITTER"
            - "BUMP"
            - "SCREAM"
            - "LADDER"
        coordinate:
          $ref: "#/components/schemas/Coordinate"
        points:
          type: "integer"
          format: "int32"
        arrows:
          type: "integer"
          format: "int32"
        planks:
          type: "integer"
          format: "int32"
        wumpusAlive:
          type: "boolean"
        hasTreasure:
          type: "boolean"
        gameCompleted:
          type: "boolean"
        death:
          type: "boolean"
      required:
      - "direction"
      - "perceptions"
      - "coordinate"
