openapi: "3.0.3"
info:
  title: "backend API"
  description: "backend API"
  version: "1.0.0"
servers:
- url: "https://backend"
paths:
  /create-account:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/CreateUser"
        required: true
      responses:
        "200":
          description: ""
          content:
            '*/*':
              schema:
                type: "object"
  /games/{id}:
    get:
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: ""
          content:
            '*/*':
              schema:
                type: "object"
  /games/{id}/action/{action}:
    post:
      description: ""
      parameters:
      - name: "action"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: ""
          content:
            '*/*':
              schema:
                type: "object"
  /games/ids:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  type: "integer"
                  format: "int32"
  /users:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/User"
  /users/{id}:
    delete:
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: ""
          content:
            '*/*':
              schema:
                type: "object"
    get:
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: ""
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    CreateUser:
      type: "object"
      properties:
        name:
          type: "string"
        password:
          type: "string"
    Object:
      type: "object"
      properties: {}
    Player:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        user:
          type: "string"
        coordinate:
          type: "array"
          items:
            type: "integer"
            format: "int32"
        points:
          type: "integer"
          format: "int32"
        arrows:
          type: "integer"
          format: "int32"
        planks:
          type: "integer"
          format: "int32"
        wumpusAlive:
          type: "boolean"
        hasTreasure:
          type: "boolean"
        gameCompleted:
          type: "boolean"
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        password:
          type: "string"
        admin:
          type: "boolean"