openapi: "3.1.0"
info:
  title: "Wumpus Game"
  description: "API to interact with the Wumpus World."
  version: "1.0.0"
paths:
  /create-account:
    post:
      tags:
        - Account
      description: "Create a new user account."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUser"
        required: true
      responses:
        "201":
          description: "The new user account has been created."
  /competitions/{id}:
    get:
      tags:
        - Competitions
      security:
        - basicAuth: []
      description: "Retrieve details of a specific competition by its ID."
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Details of the competition."
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Competition"
  /competitions/ids:
    get:
      tags:
        - Competitions
      security:
        - basicAuth: []
      description: "Retrieve a list of all competition IDs."
      responses:
        "200":
          description: "A list of competition IDs."
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  type: "integer"
                  format: "int32"
  /games/{id}:
    get:
      tags:
        - Games
      security:
        - basicAuth: []
      description: "Retrieve details of a specific game by its ID."
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Details of the game."
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Game"
  /games/{id}/action/{action}:
    post:
      tags:
        - Games
      security:
        - basicAuth: []
      description: "Perform an action in a specific game."
      parameters:
        - name: "action"
          in: "path"
          required: true
          schema:
            $ref: '#/components/schemas/Action'
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Action performed successfully."
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Player"
  /games/ids:
    get:
      tags:
        - Games
      security:
        - basicAuth: []
      description: "Retrieve a list of all game IDs."
      responses:
        "200":
          description: "A list of game IDs."
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  type: "integer"
                  format: "int32"
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    Action:
      type: string
      description: "Available actions in the Wumpus World."
      enum:
        - enter
        - restart
        - turn-left
        - turn-right
        - move-forward
        - grab
        - shoot
        - climb
    Competition:
      type: "object"
      description: "Details about a competition."
      properties:
        id:
          type: "integer"
          format: "int32"
          description: "Unique identifier for the competition."
        currentGameId:
          type: "integer"
          format: "int32"
          description: "ID of the currently active game."
        gameIds:
          type: "array"
          description: "List of game IDs associated with the competition."
          items:
            type: "integer"
            format: "int32"
      required:
        - "gameIds"
    CreateUser:
      type: "object"
      description: "Payload for creating a new user."
      properties:
        name:
          type: "string"
          description: "The name of the user."
        password:
          type: "string"
          description: "The password for the user."
      required:
        - "name"
    Game:
      type: "object"
      description: "Details about a game in the Wumpus World."
      properties:
        id:
          type: "integer"
          format: "int32"
          description: "Unique identifier for the game."
        gridSize:
          type: "integer"
          format: "int32"
          description: "The size of the grid in the game."
        pits:
          type: "integer"
          format: "int32"
          description: "The number of pits in the game."
    User:
      type: "object"
      description: "Information about a user."
      properties:
        id:
          type: "integer"
          format: "int32"
          description: "Unique identifier for the user."
        name:
          type: "string"
          description: "The name of the user."
        password:
          type: "string"
          description: "The user's password."
        admin:
          type: "boolean"
          description: "Indicates if the user has admin privileges."
        shirtColor:
          type: "string"
          description: "The color of the user's shirt."
        trouserColor:
          type: "string"
          description: "The color of the user's trousers."
        skinColor:
          type: "string"
          description: "The user's skin color."
      required:
        - "name"
        - "shirtColor"
        - "trouserColor"
        - "skinColor"
    Coordinate:
      type: "object"
      description: "Coordinates within the Wumpus World grid."
      properties:
        x:
          type: "integer"
          format: "int32"
          description: "The X-coordinate."
        y:
          type: "integer"
          format: "int32"
          description: "The Y-coordinate."
    Player:
      type: "object"
      description: "Details about a player in the Wumpus World."
      properties:
        id:
          type: "integer"
          format: "int32"
          description: "Unique identifier for the player."
        user:
          $ref: "#/components/schemas/User"
          description: "Reference to the user associated with this player."
        gameId:
          type: "integer"
          format: "int32"
          description: "ID of the game the player is participating in."
        direction:
          type: "string"
          enum:
            - "NORTH"
            - "EAST"
            - "SOUTH"
            - "WEST"
          description: "The direction the player is facing."
        perceptions:
          type: "array"
          items:
            type: "string"
            enum:
              - "STENCH"
              - "BREEZE"
              - "GLITTER"
              - "BUMP"
              - "SCREAM"
              - "LADDER"
          description: "List of current perceptions of the player."
        coordinate:
          $ref: "#/components/schemas/Coordinate"
          description: "The current coordinates of the player."
        points:
          type: "integer"
          format: "int32"
          description: "The points accumulated by the player."
        arrows:
          type: "integer"
          format: "int32"
          description: "The number of arrows the player has left."
        planks:
          type: "integer"
          format: "int32"
          description: "The number of planks the player has."
        wumpusAlive:
          type: "boolean"
          description: "Indicates if the Wumpus is still alive."
        hasTreasure:
          type: "boolean"
          description: "Indicates if the player has found the treasure."
        gameCompleted:
          type: "boolean"
          description: "Indicates if the player has completed the game."
        death:
          type: "boolean"
          description: "Indicates if the player is dead."
      required:
        - "direction"
        - "perceptions"
        - "coordinate"
