openapi: "3.0.3"
info:
  title: "backend API"
  description: "backend API"
  version: "1.0.0"
servers:
- url: "https://backend"
paths:
  /create-account:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/CreateUser"
        required: true
      responses:
        "200":
          description: ""
          content:
            '*/*':
              schema:
                type: "object"
  /games/{id}:
    get:
      description: "Get the info of one game"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Game"
  /games/{id}/action/{action}:
    post:
      description: ""
      parameters:
      - name: "action"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Player"
  /games/ids:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  type: "integer"
                  format: "int32"
  /users:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/User"
  /users/{id}:
    delete:
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: ""
          content:
            '*/*':
              schema:
                type: "object"
    get:
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/User"
components:
  schemas:
    CreateUser:
      type: "object"
      properties:
        name:
          type: "string"
        password:
          type: "string"
    Coordinate:
      type: "object"
      properties:
        x:
          type: "integer"
          format: "int32"
        "y":
          type: "integer"
          format: "int32"
    Pit:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        coordinate:
          $ref: "#/components/schemas/Coordinate"
    Wumpus:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        coordinate:
          $ref: "#/components/schemas/Coordinate"
    Treasure:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        coordinate:
          $ref: "#/components/schemas/Coordinate"
    Player:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        user:
          type: "string"
        direction:
          type: "string"
          enum:
          - "NORTH"
          - "EAST"
          - "SOUTH"
          - "WEST"
        perceptions:
          type: "array"
          items:
            type: "string"
            enum:
            - "STENCH"
            - "BREEZE"
            - "GLITTER"
            - "BUMP"
            - "SCREAM"
        coordinate:
          $ref: "#/components/schemas/Coordinate"
        points:
          type: "integer"
          format: "int32"
        arrows:
          type: "integer"
          format: "int32"
        planks:
          type: "integer"
          format: "int32"
        wumpusAlive:
          type: "boolean"
        hasTreasure:
          type: "boolean"
        gameCompleted:
          type: "boolean"
        death:
          type: "boolean"
    Game:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        gridSize:
          type: "integer"
          format: "int32"
        pits:
          type: "array"
          items:
            $ref: "#/components/schemas/Pit"
        wumpus:
          $ref: "#/components/schemas/Wumpus"
        treasure:
          $ref: "#/components/schemas/Treasure"
        players:
          type: "array"
          items:
            $ref: "#/components/schemas/Player"
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        password:
          type: "string"
        admin:
          type: "boolean"